<?php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Auth\Middleware\Authenticate as Middleware;

class Authenticate extends Middleware
{
    /**
     * Get the path the user should be redirected to when they are not authenticated.
     *
     * @param  \Illuminate\Http\Request $request
     * @return string
     */
    protected function redirectTo($request)
    {
        if (!$request->expectsJson()) {
//            return route('not_sign_in');
        }
    }
    protected function authenticate($request, array $guards)
    {
        return parent::authenticate($request, $guards); // TODO: Change the autogenerated stub
    }


}
